# Generated by Django 3.1.1 on 2020-09-10 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='join',
        ),
        migrations.AddField(
            model_name='classroom',
            name='attending',
            field=models.ManyToManyField(blank=True, related_name='class_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='action',
            field=models.IntegerField(choices=[(1, 'Change phase'), (2, 'Join'), (3, 'Leave')], default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
