# Generated by Django 3.1.1 on 2020-09-11 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_change_event_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='default_phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_of_course', to='api.phase'),
        ),
    ]
