# Generated by Django 3.1.1 on 2020-09-14 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course_default_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='class_rooms', to='api.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='default_phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_of_course', to='api.phase'),
        ),
    ]
