# Generated by Django 3.1.1 on 2020-09-14 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200914_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='timer',
        ),
    ]
