
EVENT_ACTION_CHANGE_PHASE = 1
EVENT_ACTION_JOIN = 2
EVENT_ACTION_LEAVE = 3
EVENT_ACTION_CHOICES = (
    (EVENT_ACTION_CHANGE_PHASE, 'Change phase'),
    (EVENT_ACTION_JOIN, 'Join'),
    (EVENT_ACTION_LEAVE, 'Leave')
)
